In [1]:
#!pip install tensorflow

In [1]:
#Lab Task 1
import tensorflow as tf

ts = tf.constant([11, 13, 34], dtype=tf.float32)
sc = 4.0

result_tensor = tf.multiply(ts, sc)

print("Original Tensor:", ts.numpy())
print("Scalar Value:", sc)
print("Result Tensor (After multiplying the tensor by the scalar):", result_tensor.numpy())


Original Tensor: [11. 13. 34.]
Scalar Value: 4.0
Result Tensor (After multiplying the tensor by the scalar): [ 44.  52. 136.]


In [3]:
#Lab Task 2
import tensorflow as tf

v1 = tf.constant([6.0, 5.0, 4.0], dtype=tf.float32)
v2 = tf.constant([3.0, 2.0, 1.0], dtype=tf.float32)

dot_product = tf.reduce_sum(tf.multiply(v1, v2))

print("Vector 1:", v1.numpy())
print("Vector 2:", v2.numpy())
print("Dot Product:", dot_product.numpy())

Vector 1: [6. 5. 4.]
Vector 2: [3. 2. 1.]
Dot Product: 32.0


In [4]:
#Lab Task 3
import tensorflow as tf

matrix1 = tf.constant([[1, 2],
                       [3, 4]], dtype=tf.float32)

matrix2 = tf.constant([[5, 6],
                       [7, 8]], dtype=tf.float32)

addition = tf.add(matrix1, matrix2)
print("Addition:\n", addition)

elementwise_multiplication = tf.multiply(matrix1, matrix2)
print("\nElement-wise Multiplication:\n", elementwise_multiplication)

matrix_multiplication = tf.matmul(matrix1, matrix2)
print("\nMatrix Multiplication:\n", matrix_multiplication)

Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)

Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)

Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [5]:
#Task 1
import tensorflow as tf

vector = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print("Vector:\n", vector)

scalar = tf.constant(10, dtype=tf.float32)
print("\nScalar:\n", scalar)

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)
print("\nMatrix:\n", matrix)

tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]], dtype=tf.float32)
print("\nTensor:\n", tensor)

Vector:
 tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)

Scalar:
 tf.Tensor(10.0, shape=(), dtype=float32)

Matrix:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

Tensor:
 tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


In [6]:
#Task 2
import tensorflow as tf
import numpy as np

vector = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print("Vector:")
print("Shape:", vector.shape)
print("Rank:", vector.shape.ndims)
print("Size:", np.prod(vector.shape))
print()

scalar = tf.constant(10, dtype=tf.float32)
print("Scalar:")
print("Shape:", scalar.shape)
print("Rank:", scalar.shape.ndims)
print("Size:", np.prod(scalar.shape))
print()

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)
print("Matrix:")
print("Shape:", matrix.shape)
print("Rank:", matrix.shape.ndims)
print("Size:", np.prod(matrix.shape))
print()

tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]], dtype=tf.float32)
print("Tensor:")
print("Shape:", tensor.shape)
print("Rank:", tensor.shape.ndims)
print("Size:", np.prod(tensor.shape))

Vector:
Shape: (5,)
Rank: 1
Size: 5

Scalar:
Shape: ()
Rank: 0
Size: 1.0

Matrix:
Shape: (3, 3)
Rank: 2
Size: 9

Tensor:
Shape: (2, 2, 3)
Rank: 3
Size: 12


In [7]:
#Task 3
import tensorflow as tf

tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)

print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)

Tensor 1:
tf.Tensor(
[[0.55486214 0.5962323  0.37235546 ... 0.00113392 0.80867565 0.2266823 ]
 [0.6761966  0.70991015 0.684031   ... 0.3447225  0.50948954 0.6630157 ]
 [0.01643836 0.7576051  0.14603996 ... 0.6845957  0.2561574  0.36367452]
 [0.3881414  0.40216768 0.44824827 ... 0.5983201  0.47606552 0.95391405]
 [0.7872249  0.88256586 0.91325223 ... 0.6683717  0.11647069 0.3165238 ]], shape=(5, 300), dtype=float32)

Tensor 2:
tf.Tensor(
[[0.01279891 0.903075   0.85437405 ... 0.476125   0.7625191  0.8935026 ]
 [0.5722493  0.52521324 0.52072895 ... 0.8483621  0.53268456 0.48047054]
 [0.558187   0.26567972 0.12095737 ... 0.5688611  0.5759667  0.17822862]
 [0.19442236 0.01172757 0.12966621 ... 0.67863417 0.72501075 0.8164518 ]
 [0.4163772  0.32984424 0.15496051 ... 0.6105591  0.8522787  0.4770788 ]], shape=(5, 300), dtype=float32)


In [18]:
#Task 4
import tensorflow as tf

tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)

transposed_tensor1 = tf.transpose(tensor1)
tensor_product = tf.matmul(transposed_tensor1, tensor2)

print("\nTensor product:")
print(tensor_product)


Tensor product:
tf.Tensor(
[[2.2308912  1.3677961  1.4474037  ... 1.3790394  1.0410373  1.0802085 ]
 [2.4171352  1.2616272  1.3795513  ... 1.3248119  1.2563986  1.2663528 ]
 [2.129981   1.343841   1.266767   ... 1.3175769  1.0204194  1.0299443 ]
 ...
 [1.8873376  1.0814601  1.5480609  ... 1.2678633  0.91526675 1.0029896 ]
 [2.020517   1.1448375  1.2047755  ... 1.1450894  0.91696143 0.9055192 ]
 [2.3413258  1.2578423  1.7492776  ... 1.485614   1.1355218  1.1602764 ]], shape=(300, 300), dtype=float32)


In [16]:
#Task 5
import tensorflow as tf

tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)

print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)

tensor_product = tf.tensordot(tensor1, tensor2, axes=[[1], [1]])

print("\nTensor product:")
print(tensor_product)

Tensor 1:
tf.Tensor(
[[0.2180568  0.14259338 0.8094151  ... 0.21682131 0.4069935  0.5942143 ]
 [0.68692577 0.55584896 0.3682772  ... 0.7300135  0.12563121 0.0029    ]
 [0.24717188 0.7433095  0.77224207 ... 0.88965726 0.54714036 0.39713204]
 [0.3637302  0.9977521  0.15951848 ... 0.37893057 0.698606   0.5690172 ]
 [0.68859136 0.81497216 0.59870183 ... 0.10842395 0.5095804  0.03489244]], shape=(5, 300), dtype=float32)

Tensor 2:
tf.Tensor(
[[0.94543326 0.5857998  0.8013221  ... 0.85096943 0.5251337  0.588699  ]
 [0.85442543 0.02677095 0.8476422  ... 0.79381025 0.05244565 0.10607135]
 [0.62103605 0.51705515 0.82979083 ... 0.35775113 0.9253861  0.05458331]
 [0.1642245  0.35082734 0.04186845 ... 0.37283325 0.8487637  0.7019923 ]
 [0.28357136 0.00499618 0.9307879  ... 0.2773788  0.06997311 0.8223866 ]], shape=(5, 300), dtype=float32)

Tensor product:
tf.Tensor(
[[74.95214  73.47029  74.92108  70.454544 75.5803  ]
 [75.898415 75.69577  77.69459  64.84041  72.41429 ]
 [69.43327  69.6732   72.28

In [10]:
#Task 6
import tensorflow as tf

tensor = tf.keras.layers.Input(shape=(224, 224, 3))

samples = tf.keras.backend.random_uniform(shape=(1, 224, 224, 3))

print(samples)

tf.Tensor(
[[[[0.19183636 0.2490009  0.44788826]
   [0.1002214  0.60826135 0.6038691 ]
   [0.6306559  0.22678828 0.8485068 ]
   ...
   [0.95490754 0.32131112 0.44157863]
   [0.29747224 0.8499948  0.21583176]
   [0.41099715 0.2545656  0.61371064]]

  [[0.329113   0.9079853  0.10361111]
   [0.67687833 0.178298   0.87955225]
   [0.3849944  0.9658308  0.1881274 ]
   ...
   [0.8362179  0.76185834 0.05525362]
   [0.49318886 0.10305011 0.57071877]
   [0.03721106 0.623219   0.39566183]]

  [[0.99814737 0.15771627 0.6938069 ]
   [0.6215985  0.47678447 0.6419848 ]
   [0.11806631 0.3758093  0.5155016 ]
   ...
   [0.5897635  0.46749747 0.13738751]
   [0.43654537 0.4006132  0.5648589 ]
   [0.64682794 0.48689985 0.8676344 ]]

  ...

  [[0.8339852  0.66853356 0.67775893]
   [0.9037516  0.6286489  0.3092965 ]
   [0.6453204  0.6551058  0.80720115]
   ...
   [0.05426669 0.28056276 0.80645573]
   [0.34367728 0.6754968  0.5107212 ]
   [0.80254495 0.5349715  0.8793533 ]]

  [[0.3589946  0.6789222  0.989572

In [11]:
#Task 7
import tensorflow as tf

tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1)

min_value = tf.reduce_min(tensor)
max_value = tf.reduce_max(tensor)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: tf.Tensor(3.2186508e-06, shape=(), dtype=float32)
Maximum value: tf.Tensor(0.9999994, shape=(), dtype=float32)


In [12]:
#Task 8
import tensorflow as tf

tensor = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1)

squeezed_tensor = tf.squeeze(tensor, axis=0)

print(squeezed_tensor)

tf.Tensor(
[[[0.30637705 0.36145115 0.95699096]
  [0.12703824 0.9873766  0.582216  ]
  [0.35517228 0.571144   0.3262279 ]
  ...
  [0.1915114  0.5196806  0.81011605]
  [0.7056788  0.04129565 0.8264936 ]
  [0.31408143 0.5588571  0.54674697]]

 [[0.78880894 0.6419593  0.21272361]
  [0.319057   0.16524422 0.41569912]
  [0.9823632  0.63690376 0.5648544 ]
  ...
  [0.6531632  0.50726545 0.6712805 ]
  [0.0223887  0.13888192 0.16242433]
  [0.2361058  0.17807639 0.04429805]]

 [[0.00876021 0.19529045 0.03864563]
  [0.16778028 0.28900445 0.73879385]
  [0.9364518  0.19778192 0.83775365]
  ...
  [0.55769885 0.29620087 0.6895791 ]
  [0.04326427 0.43694663 0.47479296]
  [0.640298   0.64067364 0.7407509 ]]

 ...

 [[0.46299314 0.60499275 0.44950545]
  [0.8252766  0.5620477  0.7620443 ]
  [0.01389873 0.1731981  0.5670079 ]
  ...
  [0.10574841 0.02483058 0.592765  ]
  [0.3631785  0.54164517 0.69165814]
  [0.78446424 0.72106755 0.80529165]]

 [[0.82240784 0.6698115  0.51716554]
  [0.25513422 0.6978183  0

In [10]:
#Task 9
import tensorflow as tf

tensor = tf.constant([5,8,3,9,7,6,5,4,3,2])
max_value_index=tf.reduce_max(tensor)
sess = tf.compat.v1.Session()
max_index = sess.run(max_value_index)

print("Maximum value:", tf.reduce_max(tensor))
print("Index of maximum value:", max_index)

Maximum value: Tensor("Max_1:0", shape=(), dtype=int32)
Index of maximum value: 9


In [11]:
#Task 10
max_value = tf.reduce_max(tensor)
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
one_hot_encoded = tf.one_hot(tensor, depth=max_value+1)
one_hot_encoded_result = sess.run(one_hot_encoded)
print("One-hot encoded tensor:\n",one_hot_encoded_result)

One-hot encoded tensor:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
